import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { supabaseManager } from '../../storage/supabase.js';
import { embeddingProvider, NullEmbeddingProvider } from '../../embedding/provider.js';
import { logger } from '../../logging/logger.js';
import type { FlashQueryConfig } from '../../config/loader.js';
import { acquireLock, releaseLock } from '../../services/write-lock.js';
import { validateAllTags } from '../../utils/tag-validator.js';
import { getIsShuttingDown } from '../../server/shutdown-state.js';
import {
  formatKeyValueEntry,
  shouldShowProgress,
  progressMessage,
  formatEmptyResults,
  formatMissingIds,
  joinBatchEntries,
  jsonExpectedError,
  jsonRuntimeError,
  jsonToolResult,
} from '../utils/response-formats.js';
import {
  buildMemoryResult,
  buildOrderedMemoryResults,
  type MemoryInclude,
  type MemoryRow,
} from '../utils/memory-output.js';

function formatError(err: unknown): string {
  if (!(err instanceof Error)) return String(err);
  const cause = (err as { cause?: unknown }).cause;
  if (cause instanceof Error) return `${err.message} — cause: ${cause.message}`;
  if (cause !== undefined) return `${err.message} — cause: ${JSON.stringify(cause)}`;
  return err.message;
}

type MemoryToolParams = Record<string, unknown>;

const generatedMemoryFields = new Set([
  'id',
  'memory_id',
  'version',
  'previous_version_id',
  'is_latest',
  'archived_at',
  'created_at',
  'updated_at',
  'status',
  'embedding',
]);

function expectedInvalidInput(message: string, details?: Record<string, unknown>) {
  return jsonExpectedError({ error: 'invalid_input', message, ...(details ? { details } : {}) });
}

function parseMemoryInclude(value: unknown): MemoryInclude[] {
  if (!Array.isArray(value)) return [];
  return value.filter((item): item is MemoryInclude => item === 'content' || item === 'tags_full');
}

async function resolvePluginScope(config: FlashQueryConfig, pluginScope: string | undefined): Promise<string> {
  if (!pluginScope || pluginScope === 'global') return 'global';
  try {
    const { data: matchedScope, error: rpcError } = await (supabaseManager.getClient()
      .rpc('find_plugin_scope', {
        search_name: pluginScope,
        p_instance_id: config.instance.id,
        threshold: 0.8,
      }) as Promise<{ data: string; error: { message: string } | null }>);
    if (rpcError) {
      logger.warn(`write_memory: plugin_scope lookup failed: ${rpcError.message} - defaulting to 'global'`);
      return 'global';
    }
    return matchedScope || 'global';
  } catch (err) {
    logger.warn(`write_memory: plugin_scope lookup error: ${err instanceof Error ? err.message : String(err)} - defaulting to 'global'`);
    return 'global';
  }
}

function validateWriteMemoryInput(params: MemoryToolParams) {
  if (params.mode === undefined) {
    return expectedInvalidInput('mode is required; use mode: "create" or mode: "update"');
  }
  if (params.mode !== 'create' && params.mode !== 'update') {
    return expectedInvalidInput('mode must be "create" or "update"', { field: 'mode', value: params.mode });
  }
  if (Array.isArray(params.content) || Array.isArray(params.memory_id) || Array.isArray(params.plugin_scope)) {
    return expectedInvalidInput('write_memory does not support array-like rich mutation payloads');
  }

  if (params.mode === 'create') {
    for (const field of Object.keys(params)) {
      if (field !== 'mode' && field !== 'content' && field !== 'tags' && field !== 'plugin_scope' && field !== 'include' && generatedMemoryFields.has(field)) {
        return expectedInvalidInput(`field "${field}" is generated by FlashQuery and cannot be set directly`, { field });
      }
    }
    if (typeof params.content !== 'string' || params.content.length === 0) {
      return expectedInvalidInput('content is required when mode is "create"', { field: 'content' });
    }
  }

  if (params.mode === 'update') {
    if (typeof params.memory_id !== 'string' || params.memory_id.length === 0) {
      return expectedInvalidInput('memory_id is required when mode is "update"', { field: 'memory_id' });
    }
    if (params.content === undefined && params.tags === undefined) {
      return expectedInvalidInput('mode "update" requires at least one of content or tags', { reason: 'no_mutable_fields' });
    }
    if (params.content !== undefined && typeof params.content !== 'string') {
      return expectedInvalidInput('content must be a string when provided', { field: 'content' });
    }
  }

  if (params.tags !== undefined && !Array.isArray(params.tags)) {
    return expectedInvalidInput('tags must be an array of strings', { field: 'tags' });
  }

  return null;
}

// ─────────────────────────────────────────────────────────────────────────────
// Shared semantic memory search helper — used by search_memory and search_all
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Shared semantic memory search helper. Used by search_memory and search_all.
 */
export async function searchMemoriesSemantic(
  config: FlashQueryConfig,
  query: string,
  opts: {
    tags?: string[];
    tagMatch?: 'any' | 'all';
    threshold?: number;
    limit?: number;
  }
): Promise<Array<{ id: string; content: string; tags: string[]; similarity: number; created_at: string }>> {
  const { tags, tagMatch = 'any', threshold = 0.4, limit = 10 } = opts;
  const queryEmbedding = await embeddingProvider.embed(query);
  const supabase = supabaseManager.getClient();
  const rpcResult = await supabase.rpc('match_memories', {
    query_embedding: JSON.stringify(queryEmbedding),
    match_threshold: threshold,
    match_count: limit,
    filter_tags: tags ?? null,
    filter_tag_match: tagMatch,
    filter_instance_id: config.instance.id,
  });
  const { data, error } = rpcResult as { data: unknown; error: { message: string } | null };
  if (error) throw new Error(error.message);
  return (data ?? []) as Array<{
    id: string; content: string; tags: string[]; similarity: number; created_at: string;
  }>;
}

export function registerMemoryTools(server: McpServer, config: FlashQueryConfig): void {
  server.registerTool(
    'write_memory',
    {
      description:
        'Create or update persistent memory using an explicit mode. Use mode:"create" to save a new memory, or mode:"update" to create a new latest version of an existing memory. Returns structured JSON memory identification and optional include payloads.',
      inputSchema: {
        mode: z.enum(['create', 'update']).describe('Memory write mode: create or update'),
        content: z.string().optional().describe('Memory content for create, or replacement content for update'),
        memory_id: z.string().optional().describe('Existing memory ID when mode is update'),
        tags: z.array(z.string()).optional().describe('Memory tags. In update mode this replaces the tag list.'),
        plugin_scope: z.string().optional().describe('Plugin scope for create mode. Default: global'),
        include: z.array(z.enum(['content', 'tags_full'])).optional().describe('Optional payload fields to include'),
      },
    },
    async (params: MemoryToolParams) => {
      if (getIsShuttingDown()) {
        return jsonRuntimeError('Server is shutting down; new requests cannot be processed');
      }

      const validationError = validateWriteMemoryInput(params);
      if (validationError) return validationError;

      const include = parseMemoryInclude(params.include);
      const tagsValidation = validateAllTags((params.tags as string[] | undefined) ?? []);
      if (!tagsValidation.valid) {
        return expectedInvalidInput('Tag validation failed', {
          errors: tagsValidation.errors,
          conflicts: tagsValidation.conflicts,
        });
      }

      try {
        if (config.locking.enabled) {
          const locked = await acquireLock(
            supabaseManager.getClient(),
            config.instance.id,
            'memory',
            { ttlSeconds: config.locking.ttlSeconds }
          );
          if (!locked) {
            return jsonExpectedError({
              error: 'conflict',
              message: 'Write lock timeout: another instance is writing to memory.',
              details: { reason: 'lock_contention' },
            });
          }
        }

        const supabase = supabaseManager.getClient();
        if (params.mode === 'create') {
          const resolvedScope = await resolvePluginScope(config, params.plugin_scope as string | undefined);
          const insertRow = {
            instance_id: config.instance.id,
            content: params.content as string,
            tags: tagsValidation.normalized,
            plugin_scope: resolvedScope,
            status: 'active',
            version: 1,
            previous_version_id: null,
            is_latest: true,
            archived_at: null,
            embedding: null,
          };
          const { data, error } = await supabase
            .from('fqc_memory')
            .insert(insertRow)
            .select('id, content, tags, plugin_scope, created_at, updated_at, version, previous_version_id, is_latest, archived_at')
            .single();
          if (error) throw new Error(error.message);

          const row = data as MemoryRow;
          void embeddingProvider
            .embed(params.content as string)
            .then((vector) =>
              supabaseManager
                .getClient()
                .from('fqc_memory')
                .update({ embedding: JSON.stringify(vector), updated_at: new Date().toISOString() })
                .eq('id', row.id)
            )
            .catch((err) =>
              logger.warn(
                `write_memory: background embed failed for ${row.id}: ${err instanceof Error ? err.message : String(err)}`
              )
            );

          return jsonToolResult(buildMemoryResult(row, include));
        }

        const { data: existing, error: fetchError } = await supabase
          .from('fqc_memory')
          .select('id, content, tags, plugin_scope, version, previous_version_id, is_latest, archived_at')
          .eq('id', params.memory_id as string)
          .eq('instance_id', config.instance.id)
          .single();
        if (fetchError || !existing) {
          return jsonExpectedError({
            error: 'not_found',
            message: `Memory not found: ${String(params.memory_id)}`,
            identifier: String(params.memory_id),
          });
        }
        const existingRow = existing as MemoryRow;
        if (existingRow.is_latest === false) {
          return jsonExpectedError({
            error: 'conflict',
            message: `Memory ${existingRow.id} is not the latest version`,
            identifier: existingRow.id,
            details: { reason: 'not_latest' },
          });
        }

        const nextContent = (params.content as string | undefined) ?? existingRow.content;
        const nextTags = params.tags === undefined ? (existingRow.tags ?? []) : tagsValidation.normalized;
        const { data: inserted, error: insertError } = await supabase
          .from('fqc_memory')
          .insert({
            instance_id: config.instance.id,
            content: nextContent,
            tags: nextTags,
            plugin_scope: existingRow.plugin_scope ?? 'global',
            status: 'active',
            version: (existingRow.version ?? 1) + 1,
            previous_version_id: existingRow.id,
            is_latest: true,
            archived_at: null,
            embedding: null,
          })
          .select('id, content, tags, plugin_scope, created_at, updated_at, version, previous_version_id, is_latest, archived_at')
          .single();
        if (insertError) throw new Error(insertError.message);

        const { error: updateError } = await supabase
          .from('fqc_memory')
          .update({ is_latest: false, updated_at: new Date().toISOString() })
          .eq('id', existingRow.id)
          .eq('instance_id', config.instance.id);
        if (updateError) throw new Error(updateError.message);

        const insertedRow = inserted as MemoryRow;
        void embeddingProvider
          .embed(nextContent)
          .then((vector) =>
            supabaseManager
              .getClient()
              .from('fqc_memory')
              .update({ embedding: JSON.stringify(vector), updated_at: new Date().toISOString() })
              .eq('id', insertedRow.id)
          )
          .catch((err) =>
            logger.warn(
              `write_memory: background embed failed for ${insertedRow.id}: ${err instanceof Error ? err.message : String(err)}`
            )
          );

        return jsonToolResult(buildMemoryResult(insertedRow, include));
      } catch (err) {
        const msg = formatError(err);
        logger.error(`write_memory failed: ${msg}`);
        return jsonRuntimeError(msg);
      } finally {
        if (config.locking.enabled) {
          await releaseLock(supabaseManager.getClient(), config.instance.id, 'memory');
        }
      }
    }
  );

  // save_memory: Store a persistent fact, preference, or observation
  server.registerTool(
    'save_memory',
    {
      description:
        'Store a persistent fact, preference, or observation that should be recalled in future conversations. Memories survive across sessions — use this for information the user wants remembered long-term, not for temporary notes. Tag memories for easy retrieval later. Examples: user preferences, relationship context, project decisions, things the user explicitly asks to be remembered.' +
        'Scoped by instance and tags. Tags are normalized and validated.',
      inputSchema: {
        content: z.string().describe('The memory text to store'),
        tags: z.array(z.string()).optional().describe('Tags for categorization (replaces project scoping)'),
        plugin_scope: z.string().optional().describe('Plugin scope for this memory (e.g., "crm"). Auto-corrected via fuzzy match against registered plugins. Default: "global"'),
      },
    },
    async ({ content, tags, plugin_scope }) => {
      // D-02b: Check shutdown flag immediately
      if (getIsShuttingDown()) {
        return {
          content: [
            {
              type: 'text' as const,
              text: 'Server is shutting down; new requests cannot be processed',
            },
          ],
          isError: true,
        };
      }

      try {
        if (config.locking.enabled) {
          const locked = await acquireLock(
            supabaseManager.getClient(),
            config.instance.id,
            'memory',
            { ttlSeconds: config.locking.ttlSeconds }
          );
          if (!locked) {
            return {
              content: [{ type: 'text' as const, text: 'Write lock timeout: another instance is writing to memory. Retry in a few seconds.' }],
              isError: true,
            };
          }
        }
        // Tag validation: normalize and validate before insert (D-01, D-03, TAGS-02, TAGS-03)
        const validation = validateAllTags(tags ?? []);
        if (!validation.valid) {
          const messages = [
            ...validation.errors,
            ...(validation.conflicts.length > 1
              ? [`Memory has conflicting statuses: ${validation.conflicts.join(', ')}. Choose one to keep.`]
              : []),
          ];
          return {
            content: [{ type: 'text' as const, text: `Tag validation failed: ${messages.join('; ')}` }],
            isError: true,
          };
        }

        // Resolve plugin_scope via fuzzy matching (D-07, D-08)
        let resolvedScope = 'global';
        let scopeCorrected = false;
        if (plugin_scope && plugin_scope !== 'global') {
          try {
            const { data: matchedScope, error: rpcError } = await (supabaseManager.getClient()
              .rpc('find_plugin_scope', {
                search_name: plugin_scope,
                p_instance_id: config.instance.id,
                threshold: 0.8,
              }) as Promise<{ data: string; error: { message: string } | null }>);
            if (rpcError) {
              logger.warn(`save_memory: plugin_scope lookup failed: ${rpcError.message} — defaulting to 'global'`);
            } else {
              resolvedScope = matchedScope;
              if (resolvedScope !== plugin_scope && resolvedScope !== 'global') {
                scopeCorrected = true;
              }
            }
          } catch (err) {
            logger.warn(`save_memory: plugin_scope lookup error: ${err instanceof Error ? err.message : String(err)} — defaulting to 'global'`);
          }
        }

        const supabase = supabaseManager.getClient();
        const { data, error } = await supabase
          .from('fqc_memory')
          .insert({
            instance_id: config.instance.id,
            content,
            tags: validation.normalized,
            plugin_scope: resolvedScope,
            status: 'active',
            embedding: null, // Will be populated by fire-and-forget embed below
          })
          .select('id')
          .single();
        if (error) throw new Error(error.message);
        logger.info(`save_memory: stored (id=${data.id}, tags=${validation.normalized.join(', ') || 'none'})`);

        const scopeDisplay = scopeCorrected
          ? ` Scope: ${resolvedScope} (auto-corrected from "${plugin_scope}").`
          : (plugin_scope && plugin_scope !== 'global' && resolvedScope === 'global')
            ? ` Warning: plugin "${plugin_scope}" not found — saved to global scope.`
            : ' Scope: Global.';

        // Fire-and-forget: embed after MCP response is returned (matches update_memory pattern)
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
        const newId: string = data.id;
        void embeddingProvider
          .embed(content)
          .then((vector) =>
            supabaseManager
              .getClient()
              .from('fqc_memory')
              .update({ embedding: JSON.stringify(vector), updated_at: new Date().toISOString() })
              .eq('id', newId)
          )
          .catch((err) =>
            logger.warn(
              `save_memory: background embed failed for ${newId}: ${err instanceof Error ? err.message : String(err)}`
            )
          );

        return {
          content: [
            {
              type: 'text' as const,
              text: `Memory saved (id: ${data.id}). Tags: ${validation.normalized.join(', ') || 'none'}.${scopeDisplay}`,
            },
          ],
        };
      } catch (err) {
        const msg = formatError(err);
        logger.error(`save_memory failed: ${msg}`);
        return { content: [{ type: 'text' as const, text: `Error: ${msg}` }], isError: true };
      } finally {
        if (config.locking.enabled) {
          await releaseLock(supabaseManager.getClient(), config.instance.id, 'memory');
        }
      }
    }
  );

  // search_memory: Retrieve memories by semantic similarity
  server.registerTool(
    'search_memory',
    {
      description:
        'Search memories by semantic similarity, optionally filtered by tags. Returns ranked results with match scores. Use this when the user asks "do I have a memory about X", "what did I note about Y", or when you need to recall context from previous conversations. For listing all memories with optional tag filtering (no search query), use list_memories instead.' +
        'Scoped by instance_id; filter further via optional tags.',
      inputSchema: {
        query: z.string().describe('The search query'),
        tags: z.array(z.string()).optional().describe('Filter by tags'),
        tag_match: z
          .enum(['any', 'all'])
          .optional()
          .describe(
            'How to combine multiple tags. "any" (default): items with at least one of the tags. ' +
            '"all": only items with every tag.'
          ),
        threshold: z.number().optional().describe('Minimum similarity score (0-1). Default: 0.4'),
        limit: z.number().optional().describe('Maximum number of results. Default: 10'),
      },
    },
    async ({ query, tags, threshold, limit, tag_match }) => {
      // D-02b: Check shutdown flag immediately
      if (getIsShuttingDown()) {
        return {
          content: [
            {
              type: 'text' as const,
              text: 'Server is shutting down; new requests cannot be processed',
            },
          ],
          isError: true,
        };
      }

      try {
        // EMBED-03: Proactive check for disabled embedding
        if (embeddingProvider instanceof NullEmbeddingProvider) {
          return {
            content: [{
              type: 'text' as const,
              text: 'Semantic search unavailable (no API key configured). Use tag-based search with list_memories instead.',
            }],
            isError: true,
          };
        }

        // Delegate to shared helper (also used by search_all)
        let semanticAvailable = true;
        let results: Array<{ id: string; content: string; tags: string[]; similarity: number; created_at: string }> = [];
        try {
          results = await searchMemoriesSemantic(config, query, {
            tags,
            tagMatch: tag_match ?? 'any',
            threshold,
            limit,
          });
        } catch (embedErr) {
          logger.warn(`search_memory: embedding unavailable, falling back to tag-based search: ${embedErr instanceof Error ? embedErr.message : String(embedErr)}`);
          semanticAvailable = false;
        }

        if (!semanticAvailable) {
          // Strict thresholds (>=0.5) require precise semantic scoring — return empty with a note.
          // Lenient thresholds (<0.5 or default 0.4) fall back to tag-based DB filtering.
          const effectiveThreshold = threshold ?? 0.4;
          if (effectiveThreshold >= 0.5) {
            return {
              content: [{ type: 'text' as const, text: formatEmptyResults('memories') }],
              isError: false,
            };
          }

          const supabase = supabaseManager.getClient();
          let dbQuery = supabase
            .from('fqc_memory')
            .select('id, content, tags, created_at')
            .eq('instance_id', config.instance.id)
            .eq('status', 'active')
            .order('created_at', { ascending: false })
            .limit(limit ?? 10);

          if (tags && tags.length > 0) {
            const matchMode = tag_match ?? 'any';
            if (matchMode === 'any') {
              dbQuery = dbQuery.overlaps('tags', tags);
            } else {
              dbQuery = dbQuery.contains('tags', tags);
            }
          }

          const { data: fallbackData, error: fallbackError } = await dbQuery;
          if (fallbackError) throw new Error(fallbackError.message);

          const fallbackMemories = fallbackData ?? [];
          if (fallbackMemories.length === 0) {
            return { content: [{ type: 'text' as const, text: formatEmptyResults('memories') }], isError: false };
          }

          const fallbackBlocks = fallbackMemories.map((m) => [
            formatKeyValueEntry('Memory ID', m.id),
            formatKeyValueEntry('Content', m.content),
            formatKeyValueEntry('Tags', m.tags),
            formatKeyValueEntry('Created', m.created_at),
          ].join('\n'));

          return {
            content: [{ type: 'text' as const, text: joinBatchEntries(fallbackBlocks) }],
          };
        }

        if (results.length === 0) {
          return {
            content: [{ type: 'text' as const, text: formatEmptyResults('memories') }],
            isError: false,  // Explicit: success with empty results (not an error)
          };
        }

        // Format results using key-value pairs with --- separators
        const blocks = results.map((r) => [
          formatKeyValueEntry('Memory ID', r.id),
          formatKeyValueEntry('Content', r.content),
          formatKeyValueEntry('Match Score', `${Math.round(r.similarity * 100)}%`),
          formatKeyValueEntry('Tags', r.tags),
          formatKeyValueEntry('Created', r.created_at),
        ].join('\n'));

        const responseText = joinBatchEntries(blocks);
        return {
          content: [
            {
              type: 'text' as const,
              text: responseText,
            },
          ],
        };
      } catch (err) {
        const msg = formatError(err);
        logger.error(`search_memory failed: ${msg}`);
        return { content: [{ type: 'text' as const, text: `Error: ${msg}` }], isError: true };
      }
    }
  );

  // update_memory: Update an existing memory by creating a new versioned row
  server.registerTool(
    'update_memory',
    {
      description:
        'Update an existing memory\'s content by ID. Creates a new version — the previous version is preserved for history. Use search_memory or list_memories to find the memory_id first. Use this when the user says "update the memory about X" or when a previously saved fact has changed.',
      inputSchema: {
        memory_id: z
          .string()
          .uuid()
          .describe('UUID of the memory to update. Retrieve via search_memory or list_memories.'),
        content: z.string().describe('New content to replace the existing memory text'),
        tags: z
          .array(z.string())
          .optional()
          .describe('New tags. If omitted, existing tags are preserved.'),
      },
    },
    async ({ memory_id, content, tags }) => {
      // D-02b: Check shutdown flag immediately
      if (getIsShuttingDown()) {
        return {
          content: [
            {
              type: 'text' as const,
              text: 'Server is shutting down; new requests cannot be processed',
            },
          ],
          isError: true,
        };
      }

      try {
        if (config.locking.enabled) {
          const locked = await acquireLock(
            supabaseManager.getClient(),
            config.instance.id,
            'memory',
            { ttlSeconds: config.locking.ttlSeconds }
          );
          if (!locked) {
            return {
              content: [{ type: 'text' as const, text: 'Write lock timeout: another instance is updating memory. Retry in a few seconds.' }],
              isError: true,
            };
          }
        }
        // Step 1: Fetch existing row
        const supabase = supabaseManager.getClient();
        const { data: existing, error: fetchError } = await supabase
          .from('fqc_memory')
          .select('version, tags, plugin_scope')
          .eq('id', memory_id)
          .eq('instance_id', config.instance.id)
          .single();
        if (fetchError || !existing) {
          throw new Error(fetchError?.message ?? `Memory not found: ${memory_id}`);
        }

        // Step 2: Insert new version row (embedding applied fire-and-forget after response)
        const newTags = tags ?? (existing.tags as string[]);
        const { data, error } = await supabase
          .from('fqc_memory')
          .insert({
            instance_id: config.instance.id,
            content,
            tags: newTags,
            plugin_scope: existing.plugin_scope as string,
            status: 'active',
            version: (existing.version as number) + 1,
            previous_version_id: memory_id,
            embedding: null,
          })
          .select('id')
          .single();
        if (error) throw new Error(error.message);

        logger.info(
          `update_memory: created version ${(existing.version as number) + 1} (id=${data.id}, previous=${memory_id})`
        );

        // Fire-and-forget: embed after MCP response is returned (matches create_document pattern)
        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
        const newId: string = data.id;
        void embeddingProvider
          .embed(content)
          .then((vector) =>
            supabaseManager
              .getClient()
              .from('fqc_memory')
              .update({ embedding: JSON.stringify(vector), updated_at: new Date().toISOString() })
              .eq('id', newId)
          )
          .catch((err) =>
            logger.warn(
              `update_memory: background embed failed for ${newId}: ${err instanceof Error ? err.message : String(err)}`
            )
          );

        return {
          content: [
            {
              type: 'text' as const,
              text: `Memory updated. New version id: ${data.id}. Previous version id: ${memory_id}. Version: ${(existing.version as number) + 1}.`,
            },
          ],
        };
      } catch (err) {
        const msg = formatError(err);
        logger.error(`update_memory failed: ${msg}`);
        return { content: [{ type: 'text' as const, text: `Error: ${msg}` }], isError: true };
      } finally {
        if (config.locking.enabled) {
          await releaseLock(supabaseManager.getClient(), config.instance.id, 'memory');
        }
      }
    }
  );

  // list_memories: List recent memories with optional filters
  server.registerTool(
    'list_memories',
    {
      description:
        'List memories filtered by tags, without requiring a search query. Returns all matching memories with truncated content previews and memory IDs. Use this when the user wants to browse or review memories by category — e.g. "show me my CRM memories" or "list everything tagged \'preference\'". For finding a specific memory by content, use search_memory instead.' +
        'Scoped by instance_id; filter further via optional tags.',
      inputSchema: {
        tags: z.array(z.string()).optional().describe('Filter by tags'),
        tag_match: z
          .enum(['any', 'all'])
          .optional()
          .describe(
            'How to combine multiple tags. "any" (default): items with at least one of the tags. ' +
            '"all": only items with every tag.'
          ),
        limit: z.number().optional().describe('Maximum number of results. Default: 50'),
      },
    },
    async ({ tags, limit, tag_match }) => {
      // D-02b: Check shutdown flag immediately
      if (getIsShuttingDown()) {
        return {
          content: [
            {
              type: 'text' as const,
              text: 'Server is shutting down; new requests cannot be processed',
            },
          ],
          isError: true,
        };
      }

      try {
        const supabase = supabaseManager.getClient();
        let query = supabase
          .from('fqc_memory')
          .select('id, content, tags, plugin_scope, created_at')
          .eq('instance_id', config.instance.id)
          .eq('status', 'active')
          .order('created_at', { ascending: false })
          .limit(limit ?? 50);

        if (tags && tags.length > 0) {
          const matchMode = tag_match ?? 'any';
          if (matchMode === 'any') {
            query = query.overlaps('tags', tags);
          } else {
            query = query.contains('tags', tags);
          }
        }

        const { data, error } = await query;
        if (error) throw new Error(error.message);
        const memories = (data ?? []) as Array<{
          id: string;
          content: string;
          tags: string[];
          plugin_scope: string;
          created_at: string;
        }>;
        if (memories.length === 0) {
          return { content: [{ type: 'text' as const, text: formatEmptyResults('memories') }] };
        }

        // Format results using key-value pairs with --- separators
        // Content is truncated to 200 chars for list view
        const blocks = memories.map((m) => {
          const contentPreview = m.content.length > 200 ? m.content.slice(0, 200) + '...' : m.content;
          return [
            formatKeyValueEntry('Memory ID', m.id),
            formatKeyValueEntry('Content', contentPreview),
            formatKeyValueEntry('Tags', m.tags),
            formatKeyValueEntry('Created', m.created_at),
          ].join('\n');
        });

        const responseText = joinBatchEntries(blocks);
        return {
          content: [
            {
              type: 'text' as const,
              text: responseText,
            },
          ],
        };
      } catch (err) {
        const msg = formatError(err);
        logger.error(`list_memories failed: ${msg}`);
        return { content: [{ type: 'text' as const, text: `Error: ${msg}` }], isError: true };
      }
    }
  );

  // get_memory: Retrieve one or more memories by ID
  server.registerTool(
    'get_memory',
    {
      description:
        'Retrieve one or more memories by their memory_id. Returns full content and all metadata. Pass a single ID for one memory, or an array of IDs for batch retrieval. Use this after finding memory IDs through search_memory or list_memories when you need the complete, untruncated content.' +
        'or an array of memory_id strings for batch format.',
      inputSchema: {
        memory_ids: z
          .union([z.string(), z.array(z.string())])
          .describe('Single memory ID (UUID) or array of memory IDs to retrieve'),
        include: z.array(z.enum(['content', 'tags_full'])).optional().describe('Optional memory payload fields'),
      },
    },
    async ({ memory_ids, include }) => {
      // D-02b: Check shutdown flag immediately
      if (getIsShuttingDown()) {
        return {
          content: [
            {
              type: 'text' as const,
              text: 'Server is shutting down; new requests cannot be processed',
            },
          ],
          isError: true,
        };
      }

      try {
        const isBatch = Array.isArray(memory_ids);
        const ids = isBatch ? memory_ids : [memory_ids];
        const includeFields = parseMemoryInclude(include);

        const supabase = supabaseManager.getClient();
        const { data, error } = await supabase
          .from('fqc_memory')
          .select('id, content, tags, plugin_scope, created_at, updated_at, version, previous_version_id, is_latest, archived_at')
          .in('id', ids) // 'id' NOT 'memory_id'
          .eq('instance_id', config.instance.id);

        if (error) {
          return jsonRuntimeError(`Error retrieving memories: ${(error as { message: string }).message}`);
        }

        const results = (data ?? []) as MemoryRow[];

        if (!isBatch) {
          const row = results.find((m) => m.id === ids[0]);
          if (!row) {
            return jsonExpectedError({
              error: 'not_found',
              message: `Memory not found: ${ids[0]}`,
              identifier: ids[0],
            });
          }
          return jsonToolResult(buildMemoryResult(row, includeFields));
        }

        return jsonToolResult(buildOrderedMemoryResults(ids, results, includeFields));
      } catch (err) {
        const msg = formatError(err);
        logger.error(`get_memory failed: ${msg}`);
        return jsonRuntimeError(msg);
      }
    }
  );

  // archive_memory: Archive a memory by setting status=archived and updating tags (ARC-01)
  server.registerTool(
    'archive_memory',
    {
      description:
        'Archive a memory by marking it inactive. Archived memories no longer appear in search_memory or list_memories results. Use this when a memory is outdated, wrong, or the user asks to forget something.',
      inputSchema: {
        memory_ids: z.union([z.string(), z.array(z.string())]).optional().describe('Single memory ID or array of memory IDs to archive'),
        memory_id: z.string().uuid().optional().describe('Legacy singular memory ID accepted during migration'),
      },
    },
    async ({ memory_ids, memory_id }) => {
      // D-02b: Check shutdown flag immediately
      if (getIsShuttingDown()) {
        return {
          content: [
            {
              type: 'text' as const,
              text: 'Server is shutting down; new requests cannot be processed',
            },
          ],
          isError: true,
        };
      }

      try {
        const supabase = supabaseManager.getClient();
        const idsInput = memory_ids ?? memory_id;
        if (idsInput === undefined) {
          return expectedInvalidInput('memory_ids is required', { field: 'memory_ids' });
        }
        const isBatch = Array.isArray(idsInput);
        const ids = isBatch ? idsInput : [idsInput];
        const archivedAtByRoot = new Map<string, string>();
        const results: Array<ReturnType<typeof buildMemoryResult> | { error: string; message: string; identifier: string }> = [];

        for (const id of ids) {
          const { data: chainRows, error: fetchError } = await supabase
            .from('fqc_memory')
            .select('id, content, tags, plugin_scope, status, created_at, updated_at, version, previous_version_id, is_latest, archived_at')
            .eq('instance_id', config.instance.id);
          if (fetchError) throw new Error(fetchError.message);

          const allRows = (chainRows ?? []) as Array<MemoryRow & { status?: string }>;
          const requested = allRows.find((row) => row.id === id);
          if (!requested) {
            results.push({ error: 'not_found', message: `Memory not found: ${id}`, identifier: id });
            continue;
          }
          const rootId = requested.previous_version_id ?? requested.id;
          const chain = allRows.filter((row) => row.id === rootId || row.previous_version_id === rootId || row.id === requested.previous_version_id || row.previous_version_id === requested.id);
          const existingArchivedAt = chain.find((row) => row.archived_at)?.archived_at;
          const archivedAt = existingArchivedAt ?? archivedAtByRoot.get(rootId) ?? new Date().toISOString();
          archivedAtByRoot.set(rootId, archivedAt);

          for (const row of chain.length > 0 ? chain : [requested]) {
            const existingTags: string[] = Array.isArray(row.tags) ? row.tags : [];
            const newTags = [
              ...existingTags.filter((t) => t !== '#status/active'),
              ...(existingTags.includes('#status/archived') ? [] : ['#status/archived']),
            ];
            const { error } = await supabase
              .from('fqc_memory')
              .update({ status: 'archived', tags: newTags, archived_at: archivedAt, updated_at: new Date().toISOString() })
              .eq('id', row.id)
              .eq('instance_id', config.instance.id);
            if (error) throw new Error(`Failed to archive memory: ${row.id}`);
          }

          results.push(buildMemoryResult({ ...requested, archived_at: archivedAt }, []));
        }

        logger.info(`archive_memory: archived ${ids.length} memory request(s)`);
        return jsonToolResult(isBatch ? results : results[0]);
      } catch (err) {
        const msg = formatError(err);
        logger.error(`archive_memory failed: ${msg}`);
        return jsonRuntimeError(msg);
      }
    }
  );
}
