import type { PluginTableSpec } from '../../plugins/manager.js';
import type { ErrorEnvelope } from './response-formats.js';

export const GENERATED_RECORD_FIELDS = new Set([
  'id',
  'created_at',
  'updated_at',
  'instance_id',
  'fqc_id',
  'path',
  'status',
  'last_seen_updated_at',
  'embedding',
  'embedding_updated_at',
]);

export type WriteRecordMode = 'create' | 'update';

export interface WriteRecordValidationInput {
  mode?: unknown;
  plugin_id?: unknown;
  table?: unknown;
  id?: unknown;
  data?: unknown;
}

function invalidInput(message: string, details?: Record<string, unknown>): ErrorEnvelope {
  return {
    error: 'invalid_input',
    message,
    ...(details === undefined ? {} : { details }),
  };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function rejectArrayField(input: WriteRecordValidationInput): ErrorEnvelope | null {
  for (const field of ['mode', 'plugin_id', 'table', 'id', 'data'] as const) {
    if (Array.isArray(input[field])) {
      return invalidInput('write_record is single-target; array payloads are not supported', {
        field,
        reason: 'single_target_only',
      });
    }
  }
  return null;
}

function requireStringField(
  input: WriteRecordValidationInput,
  field: 'plugin_id' | 'table' | 'id',
  mode: WriteRecordMode
): ErrorEnvelope | null {
  if (typeof input[field] === 'string' && input[field].trim().length > 0) {
    return null;
  }
  return invalidInput(`${field} is required when mode is "${mode}"`, { field });
}

function validateDataObject(input: WriteRecordValidationInput, mode: WriteRecordMode): ErrorEnvelope | null {
  if (!isPlainObject(input.data)) {
    return invalidInput(`data is required when mode is "${mode}" and must be an object`, {
      field: 'data',
    });
  }
  return null;
}

function validateDataFields(
  data: Record<string, unknown>,
  tableSpec: PluginTableSpec,
  input: WriteRecordValidationInput
): ErrorEnvelope | null {
  const allowedFields = new Set(tableSpec.columns.map((column) => column.name));
  for (const field of Object.keys(data)) {
    if (GENERATED_RECORD_FIELDS.has(field)) {
      return invalidInput(`data field "${field}" is generated by FlashQuery and cannot be set directly`, {
        field,
        plugin_id: input.plugin_id,
        table: input.table,
      });
    }
    if (!allowedFields.has(field)) {
      return invalidInput(`data field "${field}" is not declared in plugin table schema`, {
        field,
        plugin_id: input.plugin_id,
        table: input.table,
      });
    }
  }
  return null;
}

export function validateWriteRecordInput(
  input: WriteRecordValidationInput,
  tableSpec: PluginTableSpec
): ErrorEnvelope | null {
  const arrayError = rejectArrayField(input);
  if (arrayError) return arrayError;

  if (input.mode === undefined) {
    return invalidInput('mode is required; use mode: "create" or mode: "update"');
  }

  if (input.mode !== 'create' && input.mode !== 'update') {
    return invalidInput('mode must be "create" or "update"', {
      field: 'mode',
      value: input.mode,
    });
  }

  const mode = input.mode;
  const pluginError = requireStringField(input, 'plugin_id', mode);
  if (pluginError) return pluginError;
  const tableError = requireStringField(input, 'table', mode);
  if (tableError) return tableError;

  if (mode === 'create' && input.id !== undefined) {
    return invalidInput('id is not allowed when mode is "create"', { field: 'id' });
  }

  if (mode === 'update') {
    const idError = requireStringField(input, 'id', mode);
    if (idError) return idError;
  }

  const dataError = validateDataObject(input, mode);
  if (dataError) return dataError;
  const data = input.data;

  const fieldError = validateDataFields(data, tableSpec, input);
  if (fieldError) return fieldError;

  if (mode === 'create') {
    const missingFields = tableSpec.columns
      .filter((column) => column.required === true)
      .map((column) => column.name)
      .filter((field) => data[field] === undefined);
    if (missingFields.length > 0) {
      return invalidInput('mode "create" requires all schema-required data fields', {
        field: 'data',
        missing_fields: missingFields,
        plugin_id: input.plugin_id,
        table: input.table,
      });
    }
  }

  if (mode === 'update' && Object.keys(data).length === 0) {
    return invalidInput('mode "update" requires at least one mutable data field', {
      reason: 'no_mutable_fields',
    });
  }

  return null;
}
