import { defineConfig } from 'vitest/config';
import { resolve } from 'node:path';

export default defineConfig({
  test: {
    root: resolve(import.meta.dirname, '../..'),
    include: [
      'tests/integration/documents.integration.test.ts',
      'tests/integration/save-memory-tags.test.ts',
      'tests/integration/compound-tools.integration.test.ts',
      'tests/integration/llm-config-sync.test.ts',
      'tests/integration/tool-registry.test.ts',
      'tests/integration/plugin-reconciliation.integration.test.ts',
      'tests/integration/atomic-write-frontmatter.integration.test.ts',
      'tests/integration/vault-write-durable.integration.test.ts',
      'tests/integration/archive-document-lock.test.ts',
      'tests/integration/per-file-lock.test.ts',
      'tests/integration/two-tier-lock.integration.test.ts',
      'tests/integration/lock-timeout.integration.test.ts',
      'tests/integration/fqc-write-locks-drop.integration.test.ts',
      'tests/integration/lock-startup.integration.test.ts',
      'tests/integration/folder-lock.integration.test.ts',
      'tests/integration/destination-lock.integration.test.ts',
      'tests/integration/move-exdev-fallback.integration.test.ts',
      'tests/integration/manage-directory-advisory-lock.integration.test.ts',
      'tests/integration/apply-tags-concurrent.integration.test.ts',
      'tests/integration/insert-doc-link-race.integration.test.ts',
      'tests/integration/call-macro-per-step-lock.integration.test.ts',
      'tests/integration/batch-envelope.integration.test.ts',
      'tests/integration/batch-input-shape.integration.test.ts',
      'tests/integration/version-token-shape.integration.test.ts',
      'tests/integration/version-token-precondition.integration.test.ts',
      'tests/integration/version-check-inside-lock.integration.test.ts',
      'tests/integration/token-equals-disk.integration.test.ts',
      'tests/integration/refused-write-envelope.integration.test.ts',
      'tests/integration/scanner-zero-writes.integration.test.ts',
      'tests/integration/reference-resolver.integration.test.ts',
      'tests/integration/supabase-schema-verify.test.ts',
      'tests/integration/template-tools.integration.test.ts',
      'tests/integration/macro-parse-error.test.ts',
      'tests/integration/macro-shell-verbs.integration.test.ts',
      'tests/integration/macro-tool-dispatch.test.ts',
      'tests/integration/macro-concurrency.test.ts',
      'tests/integration/macro-call-macro-session.test.ts',
      'tests/integration/macro-source-ref.integration.test.ts',
      'tests/integration/macro-write-lock.integration.test.ts',
      'tests/integration/mcp-broker/client-lifecycle.test.ts',
      'tests/integration/mcp-broker/dispatch.test.ts',
      'tests/integration/mcp-broker/host-surface.test.ts',
      'tests/integration/mcp-broker/tofu-list-changed.test.ts',
      'tests/integration/mcp/tools/memory-plugin-scope.test.ts',
      'tests/integration/embedding/background-embed-doc-memory-record.test.ts',
      'tests/integration/embedding/pending-embed-worker.test.ts',
      'tests/integration/doctor/embedding-diagnostics.test.ts',
      'tests/integration/mcp/tools/records-pg-pool.test.ts',
      'tests/integration/services/scanner-embed-drain.test.ts',
      'tests/integration/server/shutdown-mcp-drain.test.ts',
      'tests/integration/memory-no-coarse-lock.integration.test.ts',
      'tests/integration/records-reconciliation.integration.test.ts',
      'tests/integration/unregister-plugin-races.integration.test.ts',
      'tests/integration/tool-search/*.test.ts',
    ],
    setupFiles: ['tests/helpers/setup-build.ts', 'tests/helpers/setup-env.ts'],
    globals: true,
    testTimeout: 30000,
    // Integration tests share module-level singletons (supabaseManager, pluginManager).
    // maxWorkers: 1 ensures one file runs at a time, preventing DDL races and singleton conflicts.
    maxWorkers: 1,
    minWorkers: 1,
  },
});
